### ISSUE TITLE
Substitution mappings grammar: Requirement mappings should be list of strings.

### ISSUE THREAD

**Issue by abhishek-kumar0409** [tliron/puccini#13]
**Sample VNFD snippet:**

topology_template:
     substitution_mappings:

       node_type: MyCompany.SunshineDB.1_0.1_0`
       #properties:
    #   flavour_id: complex
        requirements:`
            - virtual_link: [ dbBackendCp, virtual_link ]  # IPv4 for SQL
            - virtual_link: [ serviceNodeCp, virtual_link ]  # IPv4 for SSH

**Errors**

PROBLEMS (1)

    file:/home/abhishek/projects/parser/updated_vnfds/annex_2_complex.yml
    topology_template.substitution_mappings.requirements: "list" instead of "map"

Hi Tal,

The grammar of substitution mappings should support list of mappings (i.e. requirement, capabilities etc.). In one of the example, I am not able to expose more than one virtual_links present in the substitution_mapping section. The parser expects the grammar to be a map but not list. If we use map then there has to be some sort of uniqueness of the keys present in the requirement_mappings `(e.g virtual_link1, virtual_link2 or etc)`. But this approach defeats the grammar rule  as per Simple Profile v1.2. 

Do you think it's a bug...? Your thoughts please?

**Comment by abhishek-kumar0409** [comment]
For your reference purpose, I have attached the sample descriptors. I have used puccini to fix most of the errors present in tosca yaml. The experience is awesome. Just that the absence of line numbers to report the error makes the situation worse sometimes. :( 
[examples.zip](https://github.com/tliron/puccini/files/2386852/examples.zip)

**Comment by tliron** [comment]
As usual the TOSCA spec is of low quality and has contradictions. For example, see [Example 19](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.2/TOSCA-Simple-Profile-YAML-v1.2.html#_Toc454457701) and the example at 3.9.2.7.2 where the requirements are in map syntax. There are a few cases of this in the spec. But is also says in 3.8.12.1 that all the `substitution_mappings` sub-keys are lists. But then in 3.9.2 it mentions `map_of_requirement_mappings_to_expose`. Yes, map.

So, which is correct? I think map is correct, because it is most consistently used in the examples. 3.8.12.1 must be the error (one of many in the spec). All of the sub-keys in all the examples are maps.

The question of uniqueness is tricky indeed and not well defined in TOSCA. In a node *template*, you indeed have a sequenced list of requirements, because the same requirement may be specified more than once (according the `occurrences`). But then in a node *type* requirements also use the sequenced list syntax. This actually makes no grammatical sense, because at the type the requirements are identified by name plus number of occurrences. In my opinion, the TOSCA authors chose the sequenced list syntax at the node type just for consistency with the node template syntax. Indeed, if at the node type you try to use the same requirement name more than once, Puccini will consider that to be an error.

Substitution mappings might seem odd because they seem to be somewhere in between a node type and a node template. I agree that your use case presents a problem. Actually, I do think the grammar and syntax should be of a node template, not a node type, per your suggestion. But to fix this we will need clarification from OASIS.

The lack of line numbers for errors is known and mentioned in the FAQ:
> ### Why doesn't the TOSCA parser tell me which line number in the relevant file a problem occurred?
> 
> Unfortunately, [our YAML parser](https://gopkg.in/yaml.v2) doesn't expose this information. There is an [open issue](https://github.com/go-yaml/yaml/issues/108) for it, and if it's resolved we will add this important feature in the future.

**Comment by tliron** [comment]
Some more info --

How does Puccini know which requirement to map to in the destination template? Using your provided example, what happens if the `dbBackendCp` node template has more than one requirement named `virtual_link`?

The answer is that it doesn't know. Node templates actually don't *requirements*, they have *relationships*, which are requirements that are fulfilled by capabilities in other node templates. So all it does is store the requirement name. It's up to the orchestrator to "do the right thing".

But it's also entirely unclear to me what "the right thing" would be. Again, this is because substitution mapping is poorly defined in TOSCA. My best understanding is that the orchestrator would have to step back and treat the node template again as a node type and re-satisfy the requirement, effectively creating a new relationship. So, again, substitution mapping seems like something in between a node template and a node type.

**Comment by abhishek-kumar0409** [comment]
Hi Tal,

Thanks much for sharing the detailed info. We have reached out to Oasis
community couple of weeks back. Unfortunately, we didn't get any proper
resolution from them.

For the time being, the SOL-001 community folks decided to accept the
grammar of substitution mapping as list of mappings. Until they find some
suitable approach, the grammar to be used will be a list of  requirement
mappings. The external virtual links referenced in the lower level service
templates (i.e. VNFDs) will be substituted by the higher level service
templates (i.e. NSDs). And, there could be possibility of substituting
multiple virtual links from the VNFD. This was the only motivation to
accept the grammar as list but not as map. But, you can also try once to
seek an answer from them...

**Comment by abhishek-kumar0409** [comment]
Also, the grammar of substitution mapping is very confusing and there are not enough contents on web to understand. The TOSCA spec is also not enough to understand the topics. I will also do some research on web to understand more on the subject.

To answer your question, 
Using your provided example, what happens if the dbBackendCp node template has more than one requirement named virtual_link?

I understand the issue here. The parser won't be able to figure out which requirement it has to fulfill.... :( Do you think if we can add one more additional param in requirement_mappings (list of 3 strings i.e.[node_template_name, requirement_name, <some_identifier>] )to have an additional param as an identifier to uniquely identify the mappings.  Will this approach solve the issue ?

**Comment by abhishek-kumar0409** [comment]
Yes Tal, the use of flags fix will temporarily fix the issue in puccini. 

But, the better solution  would be to adhere as per the standards. We will re-trigger the conversation thread  with Oasis folks to reach some conclusion that can become a de facto standard for everyone...

**Comment by abhishek-kumar0409** [comment]
I am trying to capture my understanding based on your reply in the below example...
<pre>
node_types:
   VNF1:
          type: tosca.nodes.nfv.VNF
    VL1:
          type: tosca.nodes.nfv.VL
          properties:  
               xxxx: xxxx
    VL2
         type: tosca.nodes.nfv.VL
          properties:  
               xxxx: xxxx

topology_template:
  substitution_mappings:
    node_type: tosca.nodes.nfv.VNF
    requirements:
         VL1: [ node_template_A   , virtual_link ] # IPv4 for SQL
         VL2: [ node_template_B   ,   virtual_link ] # IPv4 for SQL
</pre>

Are you referring this approach?

With this approach, the validation of the requirement_mapping names i.e. VL1, VL2 etc in the substitution_mapping section should be relaxed.  

I have observed in the ARIA tosca parser that it was not able to recognize what is VL1 and VL2.  The requirement_name `VL1` (in substitution_mapping) will be validated  against the requirement_name `virtual_link` of the node_type tosca.nodes.nfv.VNF present in the substitution_mapping section.  As the name doesn't match, the parser results in an unknown field  or requirement error or something similar not sure.....

I'm not sure if Puccini has a similar validation logic....probably I need to test and verify it....

**Comment by tliron** [comment]
Yes, Puccini does validate that the requirements are defined in the node type (at least it's supposed to).

No, what I meant is something like this:
```
  substitution_mappings:
    node_type: MyVNF
    requirements:
         virtual_link_ipv4: [ node_template_A, virtual_link ]
         virtual_link_ipv6: [ node_template_B, virtual_link ]
```
The different is a new type `MyVNF` that has separate requirements defined.

**Comment by tliron** [comment]
The recent commit adds support for quirks. Specifically you want to use this quirk:
```
puccini-tosca compile ... -x substitution_mappings.requirements.list
```
Please verify that it allows you to parse as list.

**Comment by abhishek-kumar0409** [comment]
Thanks , I understood your example now.

Then, there is only one drawback(not with the Tosca parser) with this
approach when we are working on a complex VNF descriptor. In this case, we
will end up in defining multiple VNF definition in the sevice template e.g.
VNF_with_2_VLs (virtual_linkA, virtual_linkB) and VNF_with_3_VLs
((virtual_linkA,
virtual_linkB, virtual_linkC).

This approach was discussed in the email conversation. But it wasn't
considered as the best solution.

The good part is that the new quirks now enables Puccini to supports both
the grammars of substitution mapping. I will verify and confirm by EOD.
Thanks much :)

**Comment by abhishek-kumar0409** [comment]
Hi Tal,

I am facing some issues in setting up the Puccini. After taking the pull from master branch, I tried executing the scripts as mentioned in the README file.

Attaching the screenshot of the error. Can you please suggest how to fix the issue?

![img_20180918_181346__01](https://user-images.githubusercontent.com/8438638/45688999-72b50f80-bb70-11e8-83e7-ff154b8cb593.jpg)

**Comment by tliron** [comment]
Sorry, one file was not committed before. It should work now.

**Comment by abhishek-kumar0409** [comment]
Tal, I have verified it. The fix is working fine for me... :)

**Comment by tliron** [comment]
Thanks! Am closing.

For completion -- I also just committed [some documentation for quirks](https://github.com/tliron/puccini/blob/master/puccini-tosca/QUIRKS.md).
