### ISSUE TITLE
policies should be list not map

### ISSUE THREAD

**Issue by pmjordan** [tliron/puccini#30]
TOSCA 1.3 section 3.9.2.6.1 defines polices within a topology template as a list of policy definitions but in v0.12.0 examples/Tosca/policies-and-groups.yaml has the backup policy defined as a map. If I change it to a list like this:

policies:

    - backup:
        type: ContinuousBackup
        properties:
          frequency: .5 d
        targets:
        # Target node templates and groups must match our definition at the policy type
        # (Can include derived types)
          - server2
          - redundants

the validation fails with in the error: 
 @106,3 topology_template.policies: "!!seq" instead of "!!map"

**Comment by tliron** [comment]
First of all, you are right and this will be fixed.

Second ... this is a surprisingly complex little issue! I raised it in the TOSCA ad-hoc meeting today and nobody could explain why it is a sequenced list, when groups, etc., are maps. It may have been an error, which is indeed how I interpreted it originally. (There are many errors in the spec.)

As a list, does it mean that two policies can have the same name? Or does the list just mean a (potential) order of priority in which they are implied? For Puccini, I will decide on the latter. I can't tell you what other parsers will do, because the spec is open to interpretation.

As for the history of this confusion, check out [this section in 1.2](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.2/TOSCA-Simple-Profile-YAML-v1.2.html#_Toc454457774). You see that _all_ keywords are specified as "list of ...". That is obviously an error, and indeed existed since 1.0. So, many of us assumed that it _really_ means map.

But ... [this same section was fixed in 1.3](http://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/TOSCA-Simple-Profile-YAML-v1.3.html#_Toc454457774)... except that only policies were left as a list, and indeed in the section you mention it has stayed a list.

Maybe this was an oversight? I think it probably was, because nobody can provide a reason. :)

In any case, for better or for worst I agree.
