### ISSUE TITLE
Is topology_template valid in an imported document?

### ISSUE THREAD

**Issue by jpc4242** [tliron/puccini#51]
This is indented to be labelled as question more than a bug.

I've noticed that (using tosca 1.2 simple profile) that when a file that is imported contains `topology_template`, an error is generated:
```
@11,1 topology_template: unsupported field
```
I performed some tests (I can attach the files if you want) and the same syntax that is happily accepted in the toplevel file (i.e: the one pointed by `Entry-Definitions`) is rejected in an imported file

I tend to agree with this behavior. I understand that section 3.10.3.9 only mentions **type** definitions and `topology_template` is not a type definition. But someone may argue that 3.10.3.9 also does not explicitly forbid `topology_template`. 

That's why I'm asking: Is there any other reasoning backing this behaviour?
Or should a new quirk be needed here? (e.g: "import.only_typedef" -> import type definitions but quietly ignore anything else

**Comment by tliron** [comment]
Thanks for the question. This is indeed intentional and I hope that in TOSCA 2.0 we can make it explicit. I'm not even sure how it could be implemented. Would we merge the two lists of node templates? How will we handle name conflicts? Could a requirement in one topology be satisfied by the other?

Internally Puccini distinguishes between a [unit](https://github.com/tliron/puccini/blob/main/tosca/grammars/tosca_v2_0/unit.go), which is a TOSCA YAML file that can indeed contain types and metadata, and a [service template](https://github.com/tliron/puccini/blob/main/tosca/grammars/tosca_v2_0/service-template.go), which inherits from the "unit" and adds the `topology_template` section. Imports are handled as units, not service templates. So, effectively only the root can have `topology_template`.

By the way, you can now use the GitHub "discussions" tab if you just have question and don't intend them to be open issues.

**Comment by jpc4242** [comment]
Thank you Tal, you confirmed my opinion. 
Drawing a loose parallelism to C, an `imports` (without using namespace) acts like an `#include` and `topology_template` acts like the `main()` function. Therefore it does not make sense to include multiple files and have a main fucntion in each of them

Closing the issue (and using "Discussions" tab in the future)

**Comment by tliron** [comment]
It's not a bad analogy. Also consider that not all C programs *require* a main function. If they don't have one, we might call them a "library". The TOSCA equivalent would be a "profile".
