### ISSUE TITLE
topology_template.node_templates["vdu_node_1"].capabilities["virtual_compute"]: not enough relationships: 0 < 1

### ISSUE THREAD

**Issue by chrimann** [tliron/puccini#88]
The attached VNFD yaml fails with the problem:

topology_template.node_templates["vdu_node_1"].capabilities["virtual_compute"]: not enough relationships: 0 < 1

As far as I am aware this should be a valid VNFD. A single virtual_compute capability should be described but does not need a matching requirement.

[Files.zip](https://github.com/tliron/puccini/files/7540105/Files.zip)

**Comment by philippemerle** [comment]
Hi @chrimann, I confirm the given VNFD is correct and should mean something like this:
![test-uml2-component-diagram2](https://user-images.githubusercontent.com/770247/141832619-7d586c5c-8530-461e-81b7-727b4c8615fb.png)
I see nowhere in TOSCA 1.3 that a capability with occurrences [1, ...] shall be the target of at least one relationship template. Then a TOSCA parser should not raise an error here. However the parser could raise a warning to inform the developer that one capability is unconnected, perhaps a relationship instance is missing. Anyway this can not be considered as an error, perhaps this is a defect.

**Comment by philippemerle** [comment]
This was also discuted in https://github.com/tliron/puccini/issues/69.

**Comment by philippemerle** [comment]
Commenting Line 1248 in etsi_nfv_sol001_vnfd_2_5_1_types.yaml shows that puccini has two different behaviours when `occurrences` is present and it is not present as discussed in [#69](https://github.com/tliron/puccini/issues/69).

**Comment by chrimann** [comment]
Hi @philippemerle, thank you for your comments.  In its current state I am unable to use Puccini to validate VNFD packages, hopefully this can be addresses soon.

**Comment by tliron** [comment]
How do you understand `occurrences` in capabilities, then? What semantic meaning should it have?

I can add a quirk to support your interpretation.

**Comment by chrimann** [comment]
I interpret occurrences as the number of relationships that the capability supports, not the number it must have. There can be a surplus of capabilities to requirements.

**Comment by tliron** [comment]
I'm not sure I understand. The `occurrences` keyword is a range.

What does the lower bound mean to you? If the number is, say, 5, what does that mean?

What does the upper bound mean to you? If the number is, say, 10, what does that mean?

**Comment by chrimann** [comment]
From the tosca docs:

https://docs.oasis-open.org/tosca/TOSCA-Simple-Profile-YAML/v1.3/os/TOSCA-Simple-Profile-YAML-v1.3-os.html#_Toc26969429

The optional minimum and maximum occurrences for the capability. By default, an exported Capability should allow at least one relationship to be formed with it with a maximum of UNBOUNDED relationships.
Note: the keyword UNBOUNDED is also supported to represent any positive integer.

The words “should allow”, not “must allow“ means to me that the relationship is optional.

**Comment by tliron** [comment]
I still don't understand what you mean. If a capability allows at least one relationship to be formed with it, does it mean it would also allow zero to be formed with it? In that case I don't understand what the difference would be between [ 0, UNBOUNDED ] and [ 1, UNBOUNDED ]. And then what would [ 10, UNBOUNDED ] mean? You _could_ form 10 relationships with the capability. But what about 9? Would that not be a validation error?

If it's "optional" in the sense you interpret, then what should happen if the number of incoming relationships is out of bounds? If all options on the table, then it would imply that `occurrences` has no grammatical role at all. I hope you can answer my previous question as to how you expect a TOSCA processor to handle explicit values for lower and upper bounds.

**Comment by tliron** [comment]
While you consider how to answer my questions, I would like to reiterate that we can introduce a quirk to entirely ignore `occurrences` in capabilities when it comes to satisfying requirements. We can even add it into the `etsinfv` meta-quirk if that makes sense.

**Comment by chrimann** [comment]
So, from my understanding the tosca types are templates and the occurrences on the capabilities defines the min/max that an instance of the template must have.

So for example you might have a server template with a physical interface capability min 1 and max 4. A server instance is valid if it has 1,2,3 or 4 physical interfaces.  Not having any network cables plugged in doesn’t make the server invalid.

**Comment by tliron** [comment]
I'm sorry, but I still don't understand. What do you expect Puccini to do with a minimum of, say, 5? It sounds like you are saying this value has nothing to do with TOSCA processing but rather is a value forwarded to the orchestrator for some kind of physical validation.

**Comment by chrimann** [comment]
Yes, unless there are not enough capabilities to meet a requirement, but that would be an error against the requirement not the capabilities.

**Comment by tliron** [comment]
For the record, I don't think anybody has a clear understanding of the grammatical function of this feature. I implemented what I thought was the only thing that could make any sense. I am happy to add a quirk to disable this. (It will still show up in the compiled Clout output.) I suggest `capabilities.occurrences.ignore`.

Due to this confusion, for the work towards TOSCA 2.0 I suggested removing this keyword entirely. Indeed, the only place where `occurrences` could make any sense at all is in requirements within node _types,_ because as a sequenced list the requirements within node _templates_ could then be counted accordingly. We've also discussed that if the minimum bound of those occurrences are >0 that the requirements could be "instantiated" automatically for you. Puccini does something like that in 1.3 for the case in which `occurrences` is not specified. It's a quality-of-life courtesy. But even then I think it's not entirely clear and I question whether it's really useful. I would be in favor of removing the keyword entirely from TOSCA.

The cardinality of relationships is really domain-specific, not grammatical. Whether it's one-to-one, one-to-many, many-to-one, or a more complex inter-connection is up to your implementation. For example, you can specify cardinality as a property in the capability (an integer) or the relationship. Or it can even be an attribute -- after all, it could be something that changes at runtime, for example if connections to a database are being pooled for redundancy according to changing bandwidth needs. In the world of software-defined-everything the number of "ports" or "sockets" should be a value, not a hardcoded aspect of the type. So even for TOSCA 1.3 I would suggest that the best practice is to not use `occurrences` on capabilities at all to express resource capacity.

**Comment by tliron** [comment]
This has been implemented. To enable the quirk:
```
puccini-tosca compile test.yaml -x capabilities.occurrences.permissive
``
